-- MySQL Script generated by MySQL Workbench
-- Wed Feb  3 22:29:02 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema moneywatch
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `moneywatch` ;

-- -----------------------------------------------------
-- Schema moneywatch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `moneywatch` DEFAULT CHARACTER SET utf8 ;
USE `moneywatch` ;

-- -----------------------------------------------------
-- Table `moneywatch`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moneywatch`.`user` ;

CREATE TABLE IF NOT EXISTS `moneywatch`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(145) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moneywatch`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moneywatch`.`account` ;

CREATE TABLE IF NOT EXISTS `moneywatch`.`account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `balance` INT NULL,
  `spending` INT NULL,
  `deposits` INT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_account_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `moneywatch`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `moneywatch`.`transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `moneywatch`.`transaction` ;

CREATE TABLE IF NOT EXISTS `moneywatch`.`transaction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `memo` VARCHAR(145) NOT NULL,
  `date` DATE NOT NULL,
  `account_id` INT NOT NULL,
  `type` ENUM('Deposit','Cash Withdrawal', 'POS (Point of sale)', 'Transfer (in)', 'Transfer (out)'),
  PRIMARY KEY (`id`),
  INDEX `fk_transaction_account_idx` (`account_id` ASC),
  CONSTRAINT `fk_transaction_account`
    FOREIGN KEY (`account_id`)
    REFERENCES `moneywatch`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
